### ISSUE TITLE
点云数据除了x，y，z还读取到了一个数据，导致无法运行

### ISSUE THREAD

**Issue by zhuzil** [haoy945/DeMF#3]
points的size是20000*4，所以在points_in_boxes_part这个函数中，报错了
```python
    assert points.shape[2] == 3, \
        'points dimension should be 3, ' \
        f'but got unexpected shape {points.shape[2]}'
```

**Comment by zhuzil** [comment]
我尝试只取points数据的前三个，我认为这是x,y,z坐标，然后得到了一个报错
```
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    main()
  File "train.py", line 147, in main
    meta=meta)
  File "/content/drive/MyDrive/DeMF/mmdetection3d/mmdet3d/apis/train.py", line 351, in train_model
    meta=meta)
  File "/content/drive/MyDrive/DeMF/mmdetection3d/mmdet3d/apis/train.py", line 319, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 136, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 53, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/epoch_based_runner.py", line 32, in run_iter
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/parallel/distributed.py", line 63, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/usr/local/lib/python3.7/dist-packages/mmdet/models/detectors/base.py", line 248, in train_step
    losses = self(**data)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 116, in new_func
    return old_func(*args, **kwargs)
  File "/content/drive/MyDrive/DeMF/mmdetection3d/mmdet3d/models/detectors/base.py", line 60, in forward
    return self.forward_train(**kwargs)
  File "/content/drive/MyDrive/DeMF/demf/modeling/detectors/demfnet.py", line 168, in forward_train
    bbox_preds, *loss_inputs, gt_bboxes_ignore=gt_bboxes_ignore)
  File "/content/drive/MyDrive/DeMF/demf/modeling/heads/class_agnostic_vote_head.py", line 612, in loss
    losses_all.append(self._loss(_bbox_preds, *args, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
    return old_func(*args, **kwargs)
  File "/content/drive/MyDrive/DeMF/demf/modeling/heads/class_agnostic_vote_head.py", line 634, in _loss
    pts_semantic_mask, pts_instance_mask, bbox_preds)
  File "/content/drive/MyDrive/DeMF/demf/modeling/heads/class_agnostic_vote_head.py", line 794, in get_targets
    pts_semantic_mask, pts_instance_mask, aggregated_points
  File "/usr/local/lib/python3.7/dist-packages/mmdet/core/utils/misc.py", line 30, in multi_apply
    return tuple(map(list, zip(*map_results)))
  File "/content/drive/MyDrive/DeMF/demf/modeling/heads/class_agnostic_vote_head.py", line 836, in get_targets_single
    box_indices = box_indices_all[:, i]
IndexError: too many indices for tensor of dimension 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 890) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 193, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 189, in main
    launch(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 174, in launch
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-06_02:46:53
  host      : de2b59002235
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 890)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by chenshi3** [comment]
用的是sunrgb数据集吗

**Comment by zhuzil** [comment]
> 用的是sunrgb数据集吗

是sunrgbd数据集
我对代码做了一点修改，可以正常运行了
我首先把https://github.com/haoy945/DeMF/blob/9faedd1f33df49077659044cc2dd6f93e8c0e7cc/demf/modeling/heads/class_agnostic_vote_head.py#L834
改成了
```
            box_indices_all = gt_bboxes_3d.points_in_boxes_all(points)
```
然后将
mmdetection3中计算损失值的函数
[return (pred * weight).sum()](https://github.com/open-mmlab/mmdetection3d/blob/9556958fe1c6fe432d55a9f98781b8fdd90f4e9c/mmdet3d/models/losses/axis_aligned_iou_loss.py#L76)
改成了
```
return (pred.squeeze() * weight.T).sum()
```
因为，不改的话会报错两个矩阵无法相乘，但是我不理解的是，既然weight是全0的矩阵，为什么不直接返回0

当然我这样修改之后，代码已经能够运行了

**Comment by chenshi3** [comment]
[https://github.com/haoy945/DeMF/blob/main/configs/demf/demf_votenet.py](url)
config里默认
` dict(
        type='LoadPointsFromFile',
        coord_type='DEPTH',
        shift_height=True,
        load_dim=6,
        use_dim=[0, 1, 2]),`
读入的默认是三维x、y、z

**Comment by chenshi3** [comment]
另外，注意mmdet3d版本mmdet3d==0.18.1，使用1.0.0版本极有可能出现不兼容问题
